# Generated by Django 4.1.2 on 2022-11-10 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(max_length=100, verbose_name='Category name')),
            ],
        ),
        migrations.CreateModel(
            name='SellerOrBuyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sellerOrBuyer', models.CharField(max_length=100, verbose_name='SellerOrBuyer')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subCategoryName', models.CharField(max_length=100, verbose_name='Subcategory name')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('detail', models.CharField(max_length=250, verbose_name='Detail')),
                ('price', models.IntegerField(verbose_name='Price')),
                ('picture', models.FileField(null=True, upload_to='products/')),
                ('SubPicture', models.FileField(blank=True, null=True, upload_to='products/')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.category')),
                ('sellerOrBuyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.sellerorbuyer')),
                ('subCategory', models.ManyToManyField(null=True, to='products.subcategory')),
            ],
        ),
    ]
