# Generated by Django 4.1.2 on 2022-11-11 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_products_creater'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='SubPicture',
        ),
    ]
