# Generated by Django 4.1.2 on 2022-11-13 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_products_subpicture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='subCategory',
            field=models.ManyToManyField(blank=True, to='products.subcategory'),
        ),
    ]
