# Generated by Django 4.1.2 on 2022-11-13 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_products_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='products/sub/')),
            ],
        ),
        migrations.AlterField(
            model_name='products',
            name='picture',
            field=models.FileField(null=True, upload_to='products/sub/'),
        ),
        migrations.AddField(
            model_name='products',
            name='subPicture',
            field=models.ManyToManyField(to='products.feedfile'),
        ),
    ]
