# Generated by Django 4.1.2 on 2022-11-13 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_feedfile_alter_products_picture_products_subpicture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='subPicture',
        ),
        migrations.AddField(
            model_name='feedfile',
            name='products',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='products.products'),
        ),
        migrations.AlterField(
            model_name='products',
            name='picture',
            field=models.FileField(null=True, upload_to='products/'),
        ),
    ]
