# Generated by Django 4.1.2 on 2022-11-22 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_order_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='detail',
            field=models.TextField(max_length=600, verbose_name='Detail'),
        ),
    ]
